llm_type: gwen # example
brain:
  add_context: true
  assistant_name: Raise
  creator_name: Akira
  persona_path: default_persona
  save_memories: true
  use_memories: true
pubsub:
  input_message_topic: message_received
  processed_message_topic: message_preprocessed
discord:
  creator_id: # int
  bot_chat: # int
telegram:
  creator_id: # str, for filtering messages
weaviate:
  alpha: 0.5
  author_name: # str your name under which this program will save memories
  class_name: # str class name under which we will collect your memories
  grpc_host: localhost # everything else can stay as default
  grpc_port: 50051
  grpc_secure: false
  http_host: localhost
  http_port: 8080
  http_secure: false
  limit: 2
  max_distance: 0.6
  max_retries: 5
  retry_delay: 5
  sim_search_type: hybrid
