ai_device: null
audio_api: MME
audio_input_device: ''
audio_output_device: ''
beam_search_patience: 1.0
beam_size: 5
condition_on_previous_text: false
current_language: null
denoise_audio: false
denoise_audio_post_filter: false
device_index: null
device_out_index: null
energy: 300
faster_without_timestamps: false
initial_prompt: ''
keep_silence_length: 0.2
length_penalty: 1.0
logprob_threshold: '-1.0'
max_sentence_repetition: -1
max_silence_length: 30.0
model: small
no_repeat_ngram_size: 0
no_speech_threshold: '0.6'
normalize_enabled: true
normalize_gain_factor: 2.0
normalize_lower_threshold: -24.0
normalize_upper_threshold: -16.0
ocr_lang: en
ocr_window_name: VRChat
osc_address: /chatbox/input
osc_auto_processing_enabled: true
osc_chat_limit: 144
osc_chat_prefix: ''
osc_convert_ascii: false
osc_delay_timeout: 10
osc_delay_until_audio_playback: false
osc_delay_until_audio_playback_tag: tts
osc_initial_time_limit: 15.0
osc_ip: 127.0.0.1
osc_max_scroll_size: 30
osc_min_time_between_messages: 1.5
osc_port: 9000
osc_scroll_size: 3
osc_scroll_time_limit: 1.5
osc_send_type: chunks
osc_time_limit: 15.0
osc_type_transfer: translation_result
osc_type_transfer_split: " \U0001F310 "
osc_typing_indicator: true
pause: 1.0
phrase_time_limit: 0
plugin_settings:
  VoicevoxTTSPlugin:
    acceleration_mode:
      type: select
      value: CUDA
      values:
      - CPU
      - CUDA
      - DIRECTML
    intonation_scale: 1.0
    model:
      type: select
      value: '0'
      values:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
      - '9'
      - '10'
      - '11'
      - '12'
      - '13'
      - '14'
    model_load_btn:
      label: Load model
      style: primary
      type: button
    post_phoneme_length: 0.0
    pre_phoneme_length: 0.0
    settings_groups:
      General:
      - model
      - model_load_btn
      - acceleration_mode
      Settings:
      - speed_scale
      - volume_scale
      - intonation_scale
      - pre_phoneme_length
      - post_phoneme_length
      - voice_change_source
    speed_scale: 1.0
    voice_change_source:
      type: select
      value: Disabled
      values:
      - Disabled
      - Text to Speech (Using RVC Plugin)
    volume_scale: 1.5
plugin_timer: 2.0
plugin_timer_timeout: 15.0
plugins: {}
process_id: 0
prompt_reset_on_temperature: 0.5
push_to_talk_key: ''
realtime: false
realtime_frame_multiply: 15
realtime_frequency_time: 1.0
realtime_temperature_fallback: false
realtime_whisper_beam_size: 1
realtime_whisper_model: ''
realtime_whisper_precision: float16
repetition_penalty: 1.0
silence_cutting_enabled: true
silence_offset: -40.0
src_lang: auto
stt_type: faster_whisper
target_language: eng
temperature_fallback: true
transcription_auto_save_continous_text: false
transcription_auto_save_file: ''
transcription_save_audio_dir: ''
trg_lang: fra_Latn
tts_ai_device: cuda
tts_allow_overlapping_audio: false
tts_answer: true
tts_enabled: false
tts_model:
- en
- v3_en
tts_prosody_pitch: ''
tts_prosody_rate: ''
tts_secondary_playback_device: -1
tts_use_secondary_playback: false
tts_voice: en_0
txt_romaji: false
txt_translate: false
txt_translate_realtime: false
txt_translator: NLLB200_CT2
txt_translator_device: cpu
txt_translator_precision: float32
txt_translator_size: small
vad_confidence_threshold: 0.4
vad_enabled: true
vad_frames_per_buffer: 2000
vad_on_full_clip: false
vad_thread_num: 1
websocket_ip: 127.0.0.1
websocket_port: 5000
whisper_apply_voice_markers: false
whisper_cpu_threads: 0
whisper_num_workers: 1
whisper_precision: float32
whisper_task: transcribe
word_timestamps: false
